### PR TITLE
build: pin numpy to <2 until next tensorstore release

### PR DESCRIPTION
**Pull request by tlambert03**

### CODE REVIEW

**Comment by tlambert03** [comment]
ohhhh, numpy 2.0 just hit pypi!  :joy:  that's almost certainly what's going on here

**Comment by tlambert03** [comment]
yep, it's tensorstore, which has been fixed, but not yet released: 
https://github.com/google/tensorstore/issues/165
https://github.com/google/tensorstore/commit/3c9b9c0d516b92d60f6ac2ac05a11ff2a1502eee

pinning to `numpy<2` for now

**Comment by laramiel** [comment]
I just tagged v0.1.62 which will be built with numpy2 support.  So you should be able to test this soon.

**Comment by tlambert03** [comment]
Thank you stopping by @laramiel!  Much appreciated

**Pull request merged**
